name: Deploy
on: push

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/sendsoknad-runner:${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: GitHub Package Registry login
        run: |
          echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_REPOSITORY} --password-stdin docker.pkg.github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker build & push
        run: |
          docker build -t $IMAGE .
          docker push $IMAGE
        env:
          IMAGE: ${{ env.IMAGE }}
      - name: Deploy til dev-fss
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: nais.yml
          VAR: IMAGE=${{ env.IMAGE }},CLUSTER=dev-fss
      - name: Deploy til prod-fss
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-fss
          RESOURCE: nais.yml
          VAR: IMAGE=${{ env.IMAGE }},CLUSTER=prod-fss
